#!/usr/bin/env python3
import string
import secrets

#For password length, NIST 2019 standards essentially suggest between 8 to at
#least 64 characters in length.
#(Source:https://pages.nist.gov/800-63-3/sp800-63b.html#sec5)
#However, I am human and since I am writing this program for practice,
#14 characters is my "magic number" here.

charlist = string.printable

j = secrets.choice(charlist)

i = 1
while i < 14:
    i += 1
    j = secrets.choice(charlist) + j

ascii_computer = """
     _________
    / ======= \\
   / __________\\
  | ___________ |
  | | -       | |
  | |         | |
  | |_________| |________________________
  \=____________/                        )
  / \"\"\"\"\"\"\"\"\"\"\" \                       /
 / ::::::::::::: \                  =D-\'
(_________________)"""

print(ascii_computer + "\n")
print("Generated password:")
print(j)
